import type { ClinicalLabReference } from '@/lib/veranote/clinical-labs/types';

export const GENERAL_MEDICINE_LAB_REFERENCES: Record<string, ClinicalLabReference> = {
  lfts: {
    id: 'lfts',
    label: 'Medication-related liver test abnormalities',
    category: 'hepatic',
    specialties: ['general_medicine'],
    ranges: [
      {
        label: 'Mild transaminase elevation',
        max: 3,
        unit: 'x ULN',
        severity: 'mild',
        context: 'Trend, symptoms, bilirubin, INR, and medication risk determine concern.',
      },
      {
        label: 'Clinically significant transaminase signal',
        min: 3,
        max: 5,
        unit: 'x ULN',
        severity: 'high',
        context: 'Concern increases, especially with symptoms, bilirubin elevation, or rising trend.',
      },
      {
        label: 'Marked transaminase elevation',
        min: 5,
        unit: 'x ULN',
        severity: 'critical',
        context: 'Higher-concern range requiring prompt medication and medical evaluation context.',
      },
      {
        label: "Hy's-law pattern signal",
        min: 3,
        unit: 'x ULN plus bilirubin >2x ULN',
        severity: 'critical',
        context: 'ALT/AST elevation with bilirubin elevation raises concern for serious drug-induced liver injury if no alternative explanation.',
      },
    ],
    urgentRedFlags: ['jaundice', 'abdominal pain', 'vomiting', 'malaise', 'INR elevation', 'bilirubin elevation'],
    missingContextPrompts: ['local lab ULN', 'baseline and trend', 'bilirubin', 'alk phos', 'INR', 'symptoms', 'alcohol/hepatitis/NAFLD/other causes'],
    conservativeDecisionSupport: 'Absolute AST/ALT values cannot be fully classified without the local lab upper limit of normal and clinical context.',
    sourceRefs: [
      'AASLD drug-induced liver injury review: Hy law and liver injury pattern context.',
      'LiverTox / NCBI Bookshelf: drug-induced liver injury pattern interpretation.',
    ],
    safetyNotes: ['Avoid automatic medication titration when hepatic safety is unclear.'],
  },
  sodium: {
    id: 'sodium',
    label: 'Serum sodium',
    category: 'electrolyte',
    specialties: ['general_medicine'],
    ranges: [
      {
        label: 'Mild hyponatremia',
        min: 130,
        max: 134,
        unit: 'mEq/L',
        severity: 'mild',
        context: 'Symptoms and rate of change matter.',
      },
      {
        label: 'Moderate hyponatremia',
        min: 125,
        max: 129,
        unit: 'mEq/L',
        severity: 'moderate',
        context: 'Clinical concern increases, especially with neuro symptoms, falls, rapid decline, or interacting medications.',
      },
      {
        label: 'Severe hyponatremia',
        max: 124,
        unit: 'mEq/L',
        severity: 'critical',
        context: 'High-risk category, especially with confusion, seizure, severe weakness, or rapid onset.',
      },
    ],
    urgentRedFlags: ['seizure', 'confusion', 'severe weakness', 'falls', 'rapid sodium decline'],
    missingContextPrompts: ['symptoms', 'acuity/trend', 'glucose correction', 'volume status', 'repeat confirmation', 'other sodium-lowering medications'],
    conservativeDecisionSupport: 'Hyponatremia interpretation depends on symptoms, acuity, volume status, and confirmatory labs.',
    sourceRefs: ['Hyponatremia clinical guidelines / NCBI Bookshelf: mild, moderate, severe sodium categories.'],
    safetyNotes: ['Psychotropics such as oxcarbazepine, carbamazepine, SSRIs, and SNRIs can be relevant contributors.'],
  },
  platelets: {
    id: 'platelets',
    label: 'Platelet count',
    category: 'hematology',
    specialties: ['general_medicine'],
    ranges: [
      {
        label: 'Mild thrombocytopenia',
        min: 100,
        max: 149,
        unit: 'x10^3/uL',
        severity: 'mild',
        context: 'Often asymptomatic but trend and bleeding risk matter.',
      },
      {
        label: 'Moderate thrombocytopenia',
        min: 50,
        max: 99,
        unit: 'x10^3/uL',
        severity: 'moderate',
        context: 'Bleeding risk and medication contribution need closer review.',
      },
      {
        label: 'Severe thrombocytopenia',
        max: 49,
        unit: 'x10^3/uL',
        severity: 'critical',
        context: 'Higher bleeding-risk category requiring urgent clinical context.',
      },
    ],
    urgentRedFlags: ['active bleeding', 'petechiae/purpura', 'rapid platelet decline', 'very low platelet count'],
    missingContextPrompts: ['platelet trend', 'bleeding/bruising symptoms', 'repeat CBC', 'liver tests', 'other bleeding-risk medications'],
    conservativeDecisionSupport: 'Platelet interpretation depends on bleeding symptoms, trend, etiology, and medication context.',
    sourceRefs: [
      'NHLBI thrombocytopenia overview: adult platelet count context.',
      'AAFP thrombocytopenia review: mild/moderate/severe platelet categories.',
    ],
    safetyNotes: ['Medication-related thrombocytopenia should be reviewed with the relevant prescribing reference and local protocol.'],
  },
  qtc: {
    id: 'qtc',
    label: 'QTc interval',
    category: 'cardiac',
    specialties: ['general_medicine'],
    ranges: [
      {
        label: 'Common upper-limit context',
        max: 450,
        unit: 'ms in men / about 460 ms in women',
        severity: 'reference',
        context: 'Sex, method of correction, heart rate, and baseline matter.',
      },
      {
        label: 'Prolonged QTc context',
        min: 450,
        max: 499,
        unit: 'ms',
        severity: 'high',
        context: 'Risk-factor review is important, especially with QT-prolonging medications or electrolyte abnormalities.',
      },
      {
        label: 'High-risk QTc context',
        min: 500,
        unit: 'ms',
        severity: 'critical',
        context: 'Major risk marker for torsades de pointes in many references; local protocol/cardiology context matters.',
      },
    ],
    urgentRedFlags: ['syncope', 'palpitations', 'QTc around or above 500 ms', 'hypokalemia/hypomagnesemia', 'multiple QT-prolonging medications'],
    missingContextPrompts: ['sex', 'correction formula', 'baseline QTc', 'electrolytes', 'cardiac history', 'symptoms', 'other QT-prolonging medications'],
    conservativeDecisionSupport: 'QTc interpretation depends on patient risk factors, EKG method, trend, electrolytes, and medication combinations.',
    sourceRefs: [
      'Psychotropic QTc prolongation review: upper limit and >500 ms torsades risk context.',
      'Drug-induced QT prolongation guidance: QTc trend, electrolytes, and QT-prolonging combinations.',
    ],
    safetyNotes: ['Do not make automatic medication decisions from QTc alone without clinical context and local protocol.'],
  },
};
