import type { ClinicalLabReference } from '@/lib/veranote/clinical-labs/types';

export const PSYCHIATRY_LAB_REFERENCES: Record<string, ClinicalLabReference> = {
  lithium: {
    id: 'lithium',
    label: 'Lithium serum concentration',
    category: 'medication_level',
    specialties: ['psychiatry'],
    ranges: [
      {
        label: 'Below many common therapeutic targets',
        max: 0.59,
        unit: 'mEq/L',
        severity: 'reference',
        context: 'May be low depending on indication and whether the level was a true trough.',
      },
      {
        label: 'Common maintenance reference range',
        min: 0.6,
        max: 1.0,
        unit: 'mEq/L',
        severity: 'reference',
        context: 'Often cited for maintenance treatment; some references use an upper maintenance bound of about 1.2 mEq/L.',
      },
      {
        label: 'Common acute mania reference range',
        min: 0.8,
        max: 1.2,
        unit: 'mEq/L',
        severity: 'reference',
        context: 'Higher targets may be used acutely, but patient factors and tolerability matter.',
      },
      {
        label: 'Toxicity-risk range',
        min: 1.5,
        unit: 'mEq/L',
        severity: 'critical',
        context: 'Risk of lithium toxicity increases, especially with symptoms or renal/dehydration/interacting-medication context.',
      },
    ],
    urgentRedFlags: ['GI upset', 'coarse tremor', 'confusion', 'ataxia', 'sedation', 'weakness', 'seizures', 'arrhythmia'],
    missingContextPrompts: ['trough timing', 'dose/formulation', 'adherence', 'renal function/eGFR/creatinine', 'sodium/fluid status', 'interacting medications'],
    conservativeDecisionSupport: 'Interpret lithium levels by timing, renal function, symptoms, sodium/fluid status, and interacting medications.',
    sourceRefs: [
      'Lithium carbonate prescribing information / DailyMed: therapeutic range and toxicity warning.',
      'FDA lithium labeling: toxic concentrations are close to therapeutic concentrations.',
    ],
    safetyNotes: ['Toxicity can occur near therapeutic ranges in vulnerable clinical contexts.'],
  },
  valproate: {
    id: 'valproate',
    label: 'Valproate / divalproex level',
    category: 'medication_level',
    specialties: ['psychiatry'],
    ranges: [
      {
        label: 'Below common total-level reference range',
        max: 49,
        unit: 'mcg/mL',
        severity: 'reference',
        context: 'May be low depending on indication, formulation, timing, adherence, and total versus free level.',
      },
      {
        label: 'Common total-level reference range',
        min: 50,
        max: 100,
        unit: 'mcg/mL',
        severity: 'reference',
        context: 'Often cited for seizure/general therapeutic monitoring.',
      },
      {
        label: 'Common mania-trial upper range',
        min: 50,
        max: 125,
        unit: 'mcg/mL',
        severity: 'reference',
        context: 'Some bipolar mania labeling/trials reference this broader total-level range.',
      },
      {
        label: 'Higher safety-review range',
        min: 100,
        unit: 'mcg/mL',
        severity: 'high',
        context: 'Symptoms, free level, albumin, ammonia, LFTs, and platelets become especially important.',
      },
    ],
    urgentRedFlags: ['sedation', 'confusion', 'vomiting', 'ataxia', 'hyperammonemia', 'thrombocytopenia', 'hepatic symptoms'],
    missingContextPrompts: ['total versus free level', 'timing', 'albumin', 'LFTs', 'CBC/platelets', 'ammonia when altered', 'pregnancy potential'],
    conservativeDecisionSupport: 'Total valproate levels can be misleading when albumin is low or free fraction is elevated.',
    sourceRefs: [
      'Divalproex sodium prescribing information / DailyMed: therapeutic ranges and thrombocytopenia concentration warning.',
      'Valproate labeling: free fraction and albumin context can affect interpretation.',
    ],
    safetyNotes: ['Sedation, altered mental status, LFT abnormalities, hyperammonemia, and thrombocytopenia require safety review.'],
  },
  carbamazepine: {
    id: 'carbamazepine',
    label: 'Carbamazepine level',
    category: 'medication_level',
    specialties: ['psychiatry'],
    ranges: [
      {
        label: 'Below common therapeutic reference range',
        max: 3.9,
        unit: 'mcg/mL',
        severity: 'reference',
        context: 'May be low depending on timing, formulation, adherence, autoinduction, and indication.',
      },
      {
        label: 'Common therapeutic reference range',
        min: 4,
        max: 12,
        unit: 'mcg/mL',
        severity: 'reference',
        context: 'Often cited for carbamazepine therapeutic drug monitoring.',
      },
      {
        label: 'Above common reference range',
        min: 12.1,
        unit: 'mcg/mL',
        severity: 'high',
        context: 'Neurotoxicity, drug interactions, sodium, CBC, and hepatic context become important.',
      },
    ],
    urgentRedFlags: ['ataxia', 'dizziness', 'diplopia', 'sedation', 'rash/systemic symptoms', 'hyponatremia', 'blood dyscrasia symptoms'],
    missingContextPrompts: ['timing', 'formulation', 'adherence', 'autoinduction timing', 'interacting medications', 'CBC', 'sodium', 'LFTs'],
    conservativeDecisionSupport: 'Carbamazepine interpretation depends on timing, autoinduction, symptoms, CBC, sodium, LFTs, and interactions.',
    sourceRefs: ['Carbamazepine prescribing information / DailyMed: usual adult therapeutic levels 4 to 12 mcg/mL.'],
    safetyNotes: ['Autoinduction and CYP interactions can substantially change levels and interpretation.'],
  },
  clozapineAnc: {
    id: 'clozapine-anc',
    label: 'Clozapine ANC',
    category: 'medication_safety_lab',
    specialties: ['psychiatry'],
    ranges: [
      {
        label: 'Generally normal ANC category for non-BEN labeling context',
        min: 1500,
        unit: 'cells/uL',
        severity: 'reference',
        context: 'Common historical/current-labeling threshold category for standard ANC monitoring context.',
      },
      {
        label: 'Mild neutropenia category',
        min: 1000,
        max: 1499,
        unit: 'cells/uL',
        severity: 'mild',
        context: 'Requires current-labeling/local-protocol review; BEN status changes interpretation.',
      },
      {
        label: 'Moderate neutropenia category',
        min: 500,
        max: 999,
        unit: 'cells/uL',
        severity: 'high',
        context: 'High-risk category needing urgent prescriber/pharmacy/current-labeling review.',
      },
      {
        label: 'Severe neutropenia category',
        max: 499,
        unit: 'cells/uL',
        severity: 'critical',
        context: 'High-risk infection/neutropenia category requiring urgent protocol-guided review.',
      },
    ],
    urgentRedFlags: ['fever', 'infection symptoms', 'rapid ANC decline', 'ANC below moderate/severe category thresholds'],
    missingContextPrompts: ['current ANC', 'baseline ANC', 'BEN status', 'infection symptoms', 'lab trend', 'current labeling/local protocol'],
    conservativeDecisionSupport: 'Clozapine ANC interpretation requires current labeling, local protocol, and prescriber/pharmacy review.',
    sourceRefs: [
      'FDA clozapine safety communication: REMS removed in 2025, ANC monitoring remains recommended in prescribing information.',
      'Clozapine prescribing information: ANC monitoring categories and benign ethnic neutropenia context.',
    ],
    safetyNotes: ['REMS requirements have changed; verify current labeling, institutional workflow, and local protocol.'],
  },
};
