import type { PsychMedicationInteractionRule } from '@/lib/veranote/meds/psych-med-types';

export const PSYCH_MEDICATION_INTERACTION_RULES: PsychMedicationInteractionRule[] = [
  {
    id: 'serotonergic_stacking',
    trigger: {
      classes: ['Antidepressant'],
      combinedWith: ['serotonergic', 'trazodone', 'linezolid', 'triptan', 'tramadol', 'dextromethorphan', 'st johns wort'],
    },
    severity: 'high',
    shortWarning: 'Serotonergic stacking can raise serotonin syndrome risk.',
    clinicalReason: 'Multiple serotonergic agents or a serotonergic medication plus a high-risk interacting drug can increase toxicity risk.',
    recommendedCheck: 'Review all serotonergic agents, recent dose changes, and toxicity symptoms.',
    veraResponseInstruction: 'State the interaction concern directly, mention serotonin syndrome risk, and tell the user to verify with a current interaction reference.',
  },
  {
    id: 'ssri_snri_maoi',
    trigger: {
      drugIds: ['fluoxetine', 'sertraline', 'paroxetine', 'citalopram', 'escitalopram', 'fluvoxamine', 'vilazodone', 'vortioxetine', 'venlafaxine', 'desvenlafaxine', 'duloxetine', 'levomilnacipran', 'trazodone'],
      combinedWith: ['maoi', 'phenelzine', 'tranylcypromine', 'selegiline', 'linezolid', 'methylene blue'],
    },
    severity: 'critical',
    shortWarning: 'SSRI or SNRI exposure with an MAOI-pattern interaction can be dangerous.',
    clinicalReason: 'This combination can substantially increase serotonin syndrome and other severe adverse-effect risk.',
    recommendedCheck: 'Verify active and recent MAOI exposure, washout timing, and current prescribing references before giving any transition guidance.',
    veraResponseInstruction: 'Do not give transition instructions from memory; flag the risk and require current-reference verification.',
  },
  {
    id: 'maoi_tyramine_sympathomimetic',
    trigger: {
      drugIds: ['phenelzine', 'tranylcypromine', 'selegiline_transdermal'],
      combinedWith: ['tyramine', 'pseudoephedrine', 'phenylephrine', 'amphetamine', 'methylphenidate'],
    },
    severity: 'critical',
    shortWarning: 'MAOIs can interact dangerously with tyramine-rich or sympathomimetic exposures.',
    clinicalReason: 'Hypertensive reactions and serious toxicity risk can occur with contraindicated combinations or exposures.',
    recommendedCheck: 'Verify the exact MAOI product, dose, dietary context, and all OTC or stimulant exposures.',
    veraResponseInstruction: 'Flag the interaction sharply and avoid giving definitive management without current-reference verification.',
  },
  {
    id: 'qt_stacking',
    trigger: {
      drugIds: ['citalopram', 'escitalopram', 'ziprasidone', 'haloperidol', 'chlorpromazine', 'pimozide', 'methadone', 'quetiapine'],
      combinedWith: ['qt', 'qt risk', 'qtc', 'qt prolonging medication', 'ondansetron', 'macrolide', 'fluoroquinolone', 'antiarrhythmic'],
    },
    severity: 'high',
    shortWarning: 'Additive QT risk may warrant EKG and electrolyte review.',
    clinicalReason: 'Stacking QT-risk agents or adding them to cardiac or electrolyte risk can increase torsades concern.',
    recommendedCheck: 'Review cardiac history, electrolyte risk, current EKG data, and the full medication list.',
    veraResponseInstruction: 'Mention additive QT risk, advise EKG/electrolyte review when clinically relevant, and avoid false reassurance.',
  },
  {
    id: 'antipsychotic_polypharmacy',
    trigger: {
      classes: ['Antipsychotic'],
      combinedWith: ['antipsychotic'],
    },
    severity: 'moderate',
    shortWarning: 'Antipsychotic polypharmacy deserves deliberate review.',
    clinicalReason: 'Using more than one antipsychotic can increase EPS, sedation, metabolic burden, and QT-risk depending on the agents.',
    recommendedCheck: 'Clarify indication, cross-taper status, target symptoms, and monitoring plan.',
    veraResponseInstruction: 'Frame this as a caution rather than an automatic prohibition, and avoid implying equivalence across all combinations.',
  },
  {
    id: 'clozapine_monitoring_bundle',
    trigger: {
      drugIds: ['clozapine'],
    },
    severity: 'critical',
    shortWarning: 'Clozapine requires dedicated monitoring and safety review.',
    clinicalReason: 'ANC-related monitoring, myocarditis concern, constipation/ileus risk, and seizure risk are high-yield clozapine issues.',
    recommendedCheck: 'Review ANC/CBC status, bowel regimen or constipation symptoms, cardiac symptoms, smoking changes, and seizure history.',
    veraResponseInstruction: 'Always mention that monitoring requirements and adverse-effect review are central to any clozapine question.',
  },
  {
    id: 'lithium_nsaid_ace_arb_diuretic',
    trigger: {
      drugIds: ['lithium'],
      combinedWith: ['nsaid', 'ibuprofen', 'naproxen', 'ace inhibitor', 'arb', 'lisinopril', 'losartan', 'diuretic', 'hydrochlorothiazide'],
    },
    severity: 'high',
    shortWarning: 'These combinations can raise lithium levels or toxicity risk.',
    clinicalReason: 'NSAIDs, ACE inhibitors, ARBs, and diuretics can reduce lithium clearance or destabilize volume status.',
    recommendedCheck: 'Review renal function, hydration status, lithium level timing, and the exact co-medication.',
    veraResponseInstruction: 'State the toxicity concern clearly and require verification against current references.',
  },
  {
    id: 'lithium_dehydration_toxicity',
    trigger: {
      drugIds: ['lithium'],
      combinedWith: ['dehydration', 'vomiting', 'diarrhea', 'acute kidney injury'],
    },
    severity: 'high',
    shortWarning: 'Dehydration or acute illness can increase lithium toxicity risk.',
    clinicalReason: 'Volume depletion and renal impairment can increase lithium exposure even without a new medication.',
    recommendedCheck: 'Review recent illness, oral intake, renal function, and lithium level if available.',
    veraResponseInstruction: 'Mention toxicity symptoms and avoid giving dose-adjustment instructions from memory.',
  },
  {
    id: 'valproate_lamotrigine_rash',
    trigger: {
      drugIds: ['lamotrigine'],
      combinedWith: ['divalproex', 'valproic acid', 'valproate'],
    },
    severity: 'critical',
    shortWarning: 'Valproate with lamotrigine can increase rash and SJS risk.',
    clinicalReason: 'Valproate raises lamotrigine exposure, which changes titration and increases severe rash risk.',
    recommendedCheck: 'Verify the current titration plan and the exact formulation and timing of both agents.',
    veraResponseInstruction: 'Do not supply a titration schedule from memory; flag the interaction and direct the user to current prescribing references.',
  },
  {
    id: 'carbamazepine_cyp_induction',
    trigger: {
      drugIds: ['carbamazepine'],
      combinedWith: ['psychotropic', 'antipsychotic', 'antidepressant', 'oral contraceptive', 'warfarin'],
    },
    severity: 'high',
    shortWarning: 'Carbamazepine can lower levels of many co-medications through enzyme induction.',
    clinicalReason: 'Its induction burden can reduce exposure or complicate titration of many medications.',
    recommendedCheck: 'Review the full medication list for enzyme-substrate interactions and agent-specific guidance.',
    veraResponseInstruction: 'State the broad induction caution and avoid implying predictable level effects without current-reference verification.',
  },
  {
    id: 'benzodiazepine_opioid_alcohol_sedative',
    trigger: {
      classes: ['Anxiolytic / sedative'],
      combinedWith: ['opioid', 'methadone', 'buprenorphine', 'alcohol', 'sedative'],
    },
    severity: 'critical',
    shortWarning: 'Benzodiazepines plus opioids, alcohol, or other sedatives can increase respiratory suppression risk.',
    clinicalReason: 'Sedative stacking can increase overdose, falls, and respiratory depression risk.',
    recommendedCheck: 'Review all sedating substances, overdose history, and current respiratory risk.',
    veraResponseInstruction: 'State the respiratory suppression concern clearly and avoid minimizing the risk because one agent is “low dose.”',
  },
  {
    id: 'stimulant_mania_psychosis',
    trigger: {
      classes: ['ADHD medication'],
      combinedWith: ['mania', 'psychosis', 'bipolar disorder'],
    },
    severity: 'high',
    shortWarning: 'Stimulants can worsen mania or psychosis in susceptible patients.',
    clinicalReason: 'Dopaminergic and noradrenergic activation can aggravate manic or psychotic symptoms.',
    recommendedCheck: 'Clarify the current symptom state, bipolar history, and whether mood-stabilizing coverage is documented.',
    veraResponseInstruction: 'Frame this as a clinical caution and avoid presenting stimulants as routine if mania or psychosis remains active.',
  },
  {
    id: 'antidepressant_without_mood_stabilizer',
    trigger: {
      classes: ['Antidepressant'],
      combinedWith: ['bipolar disorder', 'mania history', 'no mood stabilizer'],
    },
    severity: 'high',
    shortWarning: 'Antidepressant use in bipolar-spectrum illness without mood-stabilizing coverage may increase switch risk.',
    clinicalReason: 'Antidepressants can contribute to mood destabilization in susceptible patients.',
    recommendedCheck: 'Review bipolar history, current symptom pattern, and whether mood-stabilizing coverage is documented.',
    veraResponseInstruction: 'State the switch-risk caution without turning it into a universal prohibition.',
  },
  {
    id: 'anticholinergic_burden',
    trigger: {
      drugIds: ['amitriptyline', 'doxepin', 'benztropine', 'trihexyphenidyl', 'diphenhydramine', 'clozapine', 'olanzapine', 'quetiapine'],
      combinedWith: ['anticholinergic', 'constipating medication'],
    },
    severity: 'moderate',
    shortWarning: 'Stacked anticholinergic burden can worsen delirium, constipation, falls, or urinary retention.',
    clinicalReason: 'Combining anticholinergic medications can increase cognitive and GI adverse effects, especially in older or medically fragile patients.',
    recommendedCheck: 'Review bowel function, urinary retention risk, cognition, and the total anticholinergic burden.',
    veraResponseInstruction: 'Mention the burden and the vulnerable populations rather than only listing side effects.',
  },
  {
    id: 'seizure_threshold_lowering',
    trigger: {
      drugIds: ['bupropion', 'clozapine', 'chlorpromazine', 'olanzapine', 'tramadol'],
      combinedWith: ['seizure disorder', 'eating disorder', 'alcohol withdrawal', 'other seizure-threshold-lowering medication'],
    },
    severity: 'high',
    shortWarning: 'This combination of medication and clinical context can increase seizure risk.',
    clinicalReason: 'Several psychotropics lower seizure threshold, and risk rises with vulnerable comorbidities or stacked exposures.',
    recommendedCheck: 'Review seizure history, eating-disorder history, alcohol withdrawal risk, and the full medication list.',
    veraResponseInstruction: 'State the seizure-risk concern directly and avoid casual reassurance.',
  },
  {
    id: 'bleeding_risk_ssri_snri',
    trigger: {
      classes: ['Antidepressant'],
      drugIds: ['fluoxetine', 'sertraline', 'paroxetine', 'citalopram', 'escitalopram', 'fluvoxamine', 'vilazodone', 'vortioxetine', 'venlafaxine', 'desvenlafaxine', 'duloxetine', 'levomilnacipran'],
      combinedWith: ['nsaid', 'aspirin', 'anticoagulant', 'antiplatelet', 'warfarin', 'apixaban'],
    },
    severity: 'moderate',
    shortWarning: 'SSRI or SNRI combinations with bleeding-risk medications may increase bleeding concern.',
    clinicalReason: 'Serotonin reuptake inhibition may increase bleeding risk, especially when combined with antiplatelet or anticoagulant therapy.',
    recommendedCheck: 'Review GI bleed history, current anticoagulant or antiplatelet exposure, and the full medication list.',
    veraResponseInstruction: 'Mention bleeding-risk stacking and avoid declaring the combination safe from memory.',
  },
  {
    id: 'hyponatremia_older_adults',
    trigger: {
      drugIds: ['sertraline', 'fluoxetine', 'paroxetine', 'citalopram', 'escitalopram', 'fluvoxamine', 'venlafaxine', 'desvenlafaxine', 'duloxetine', 'oxcarbazepine', 'carbamazepine'],
      combinedWith: ['older adult', 'diuretic', 'hyponatremia'],
    },
    severity: 'moderate',
    shortWarning: 'Hyponatremia risk is higher in older adults and with some co-medications.',
    clinicalReason: 'Several antidepressants and anticonvulsants are associated with SIADH or hyponatremia risk.',
    recommendedCheck: 'Review age, sodium history, diuretic use, and current symptoms that could reflect low sodium.',
    veraResponseInstruction: 'Mention sodium monitoring or review when the context fits, especially in older adults.',
  },
  {
    id: 'metabolic_monitoring_sga',
    trigger: {
      drugIds: ['clozapine', 'olanzapine', 'quetiapine', 'risperidone', 'paliperidone', 'aripiprazole', 'brexpiprazole', 'cariprazine', 'asenapine', 'lurasidone'],
    },
    severity: 'moderate',
    shortWarning: 'Second-generation antipsychotics often need metabolic monitoring.',
    clinicalReason: 'Weight, glucose, and lipid changes can emerge or worsen on SGAs, with burden varying by agent.',
    recommendedCheck: 'Review weight or BMI, glucose or A1c, lipids, and whether recent baseline monitoring is documented.',
    veraResponseInstruction: 'Mention metabolic monitoring expectations, especially for higher-burden agents.',
  },
  {
    id: 'ekg_qtc_monitoring_trigger',
    trigger: {
      drugIds: ['citalopram', 'ziprasidone', 'haloperidol', 'chlorpromazine', 'pimozide', 'methadone', 'thioridazine'],
      combinedWith: ['syncope', 'arrhythmia', 'electrolyte abnormality', 'qt', 'qtc', 'qt prolonging medication'],
    },
    severity: 'high',
    shortWarning: 'QTc or EKG review may be important in this context.',
    clinicalReason: 'Certain agents have higher QT concern, especially with cardiac history, syncope, electrolyte risk, or other QT-prolonging medications.',
    recommendedCheck: 'Review EKG data, electrolyte status, cardiac history, and the full medication list.',
    veraResponseInstruction: 'Mention EKG/QTc review when the risk context is present and avoid false reassurance.',
  },
];
